### ISSUE TITLE
Improve the configuration instructions

### ISSUE THREAD

**Issue by ahukkanen** [OpenSourcePolitics/decidim-module-cleaner#12]
I believe there is currently a mistake in the configuration instructions:
https://github.com/OpenSourcePolitics/decidim-module-cleaner/blob/0086c624c03b701f9ea5a4013bb84ab0cbd0a079/README.md?plain=1#L25-L37

The crontab format should contain 5 parts to indicate the time of the command run but the instructions include 6 parts.

I believe the intention is to run these jobs once per day (?).

Also, I would like to suggest not assuming everyone uses Sidekiq to run these jobs, so it would be great if you could make the documentation a bit more generalized similarly as we have in Decidim documentation:

https://docs.decidim.org/en/develop/install/index.html#_scheduled_tasks

**Comment by Quentinchampenois** [comment]
Nice catch, we will improve documentation and fix cron rules ASAP ! Thanks
