### ISSUE TITLE
Delete warning email sending time potentially excludes some users after introduction of the module

### ISSUE THREAD

**Issue by ahukkanen** [OpenSourcePolitics/decidim-module-cleaner#13]
I spend quite some time trying to understand these two lines in the query that fetches the users to be warned about the account removal:

https://github.com/OpenSourcePolitics/decidim-module-cleaner/blob/0086c624c03b701f9ea5a4013bb84ab0cbd0a079/app/jobs/decidim/cleaner/clean_inactive_users_job.rb#L13-L14

If the retention period is set to 365 days (as default), this will only find users who have logged in 366 days ago (during that whole day).

This makes sense if the job is run once as per day as I believe is the intention (not sure about that, see #12).

But what if we are introducing this module to a new instance and start to run this "on the fly" after the instance has been running for years? On the first run of the job, the users who last logged in more than 366 days ago would not get warned about the account deletion which might be a problem.

It might be a bit cumbersome to solve this issue, as there would be a need to store some extra data per each user, so I'm not sure how to solve this properly either. Just wanted to report this issue that I noticed when going through the code.

Even if you don't want to change the current behavior, I would suggest adding some code comments before that query linked above to better explain its intention. It took me a while to understand.

**Comment by ahukkanen** [comment]
Just another point I also wanted to point out regarding this is that what if the job fails to run some day? E.g. there was an error on the server or the server was down due to a maintenance break.

In this situation, some users might also not receive the deletion warning.

**Comment by Quentinchampenois** [comment]
Thank you @ahukkanen for these points ! 

I agree we should ensure that users have received a warning before deletion. I will suggest different solutions to change the behaviour, maybe : 
- When user receive warning we could keep a timestamp
- Then we could clear data based on these timestamps

We will think about it ASAP, don't hesitate to make other suggestions / issues !

**Comment by Quentinchampenois** [comment]
Closed by #21
